FROM node:14.6.0-alpine

MAINTAINER yuliang <yu.liang@freelog.com>

RUN mkdir -p /data/freelog-node-provider

WORKDIR /data/freelog-node-provider

COPY . /data/freelog-node-provider

RUN npm config set registry http://registry.npm.taobao.org
RUN npm install --production

ENV NODE_ENV prod
ENV EGG_SERVER_ENV prod
ENV PORT 7105
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

EXPOSE 7105

CMD [ "npm", "start" ]
