FROM daocloud.io/node:8.5-alpine

MAINTAINER yuliang <yu.liang@freelog.com>

RUN mkdir -p /data/freelog-node-provider

WORKDIR /data/freelog-node-provider

COPY . /data/freelog-node-provider

RUN npm install

ENV NODE_ENV test
ENV EGG_SERVER_ENV test
ENV PORT 5005

EXPOSE 5005

CMD [ "npm", "start" ]
